//------------------------------------------------------------------------------
// <auto-generated>
// This code was not generated by a tool, this comment is to avoid the code analysis inspection.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace JsonSerializerApp.Entities
{
    public class BadEnumerable : IDictionary<string, object>
    {
        public object this[string key] { get => null; set => throw new NotImplementedException(); }

        public ICollection<string> Keys => null;

        public ICollection<object> Values => null;

        public int Count => 0;

        public bool IsReadOnly => true;

        public void Add(string key, object value)
        {
            return;
        }

        public void Add(KeyValuePair<string, object> item)
        {
            return;
        }

        public void Clear()
        {
            return;
        }

        public bool Contains(KeyValuePair<string, object> item)
        {
            return false;
        }

        public bool ContainsKey(string key)
        {
            return false;
        }

        public void CopyTo(KeyValuePair<string, object>[] array, int arrayIndex)
        {
            return;
        }

        public IEnumerator<KeyValuePair<string, object>> GetEnumerator()
        {
            // Primavera.Core.Patterns.Money
            return null;
        }

        public bool Remove(string key)
        {
            return false;
        }

        public bool Remove(KeyValuePair<string, object> item)
        {
            return false;
        }

        public bool TryGetValue(string key, [MaybeNullWhen(false)] out object value)
        {
            value = null;
            return false;
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            // ISSUE: 
            // This will raise an error when serializing because the IEnumerable is bad implemented.
            // That's the same issue of Primavera.Core.Patterns.Money.

            return null;
        }
    }
}
