//------------------------------------------------------------------------------
// <auto-generated>
// This code was not generated by a tool, this comment is to avoid the code analysis inspection.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace JsonSerializerApp.Entities
{
    [DebuggerDisplay("{Name}")]
    public class CircularReference
    {
        #region Public Properties

        public Guid Id { get; set; }

        public string Name { get; set; }

        public BadEnumerable Items { get; set; }

        public CircularReference Parent { get; set; }

        public IList<CircularReference> Children { get; private set; }

        #endregion

        #region Constructors

        public CircularReference(string name)
        {
            this.Id = Guid.NewGuid();
            this.Name = name;
            this.Items = new BadEnumerable();
            this.Children = new List<CircularReference>();
        }

        #endregion

        #region Public Methods

        public CircularReference AddChildren(CircularReference value)
        {
            value.Parent = this;
            this.Children.Add(value);
            return this;
        }

        public CircularReference SetParent(CircularReference value)
        {
            this.Parent = value;
            this.Parent.Children.Add(this);
            return this;
        }

        #endregion
    }
}